FROM @BASE_IMAGE@

SHELL @SHELL@

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends libboost-dev libboost-filesystem-dev cmake git build-essential

COPY scripts /scripts

ENTRYPOINT @SHELL@
