FROM @BASE_IMAGE@

SHELL @SHELL@

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends cmake build-essential curl ca-certificates

RUN mkdir -p tmp/boost && cd $_ \
  && curl -fsSL https://dl.bintray.com/boostorg/release/@BOOST_VERSION@/source/boost_@BOOST_VERSION_U@.tar.gz | tar -xz --strip-components=1 \
  && ./bootstrap.sh \
  && ./b2 cxxflags=-fPIC cflags=-fPIC -a -d0 link=static --with-filesystem --with-system install

COPY scripts /scripts

ENTRYPOINT @SHELL@
